"""new colimns in user model

Revision ID: 28752e811109
Revises: dcc855c5fbb5
Create Date: 2020-09-12 21:48:32.503906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28752e811109'
down_revision = 'dcc855c5fbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
