"""added is_new attr to Message

Revision ID: 97e4aabc7619
Revises: da68585dc178
Create Date: 2021-01-20 23:39:10.915411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e4aabc7619'
down_revision = 'da68585dc178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_new', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_new')
    # ### end Alembic commands ###
